package cn.gjb151b.outline.model;

import java.util.Date;

public class ManageSysDevelop {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_id
     *
     * @mbggenerated
     */
    private Integer devId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_itemid
     *
     * @mbggenerated
     */
    private String devItemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_name
     *
     * @mbggenerated
     */
    private String devName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_subsys_eqp
     *
     * @mbggenerated
     */
    private Integer devSubsysEqp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_subsys_eqp_name
     *
     * @mbggenerated
     */
    private String devSubsysEqpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_subsys_eqp_model
     *
     * @mbggenerated
     */
    private String devSubsysEqpModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_subsys_eqp_num
     *
     * @mbggenerated
     */
    private String devSubsysEqpNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_supplier
     *
     * @mbggenerated
     */
    private String devSupplier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_primary_platform
     *
     * @mbggenerated
     */
    private Integer devPrimaryPlatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_secondary_platform
     *
     * @mbggenerated
     */
    private Integer devSecondaryPlatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_attribute
     *
     * @mbggenerated
     */
    private Integer devAttribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_key
     *
     * @mbggenerated
     */
    private Integer devKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_install
     *
     * @mbggenerated
     */
    private Integer devInstall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_GND
     *
     * @mbggenerated
     */
    private Integer devGnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_special
     *
     * @mbggenerated
     */
    private Integer devSpecial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_interport
     *
     * @mbggenerated
     */
    private Integer devInterport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_lowsensitive
     *
     * @mbggenerated
     */
    private Integer devLowsensitive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_emp
     *
     * @mbggenerated
     */
    private Integer devEmp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_static
     *
     * @mbggenerated
     */
    private Integer devStatic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_powerport
     *
     * @mbggenerated
     */
    private String devPowerport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_powersupply
     *
     * @mbggenerated
     */
    private String devPowersupply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_voltage
     *
     * @mbggenerated
     */
    private String devVoltage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_voltagenum
     *
     * @mbggenerated
     */
    private String devVoltagenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_antenna
     *
     * @mbggenerated
     */
    private Integer devAntenna;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_receive_launch
     *
     * @mbggenerated
     */
    private Integer devReceiveLaunch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_modulation
     *
     * @mbggenerated
     */
    private Integer devModulation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_create_time
     *
     * @mbggenerated
     */
    private Date devCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_new_time
     *
     * @mbggenerated
     */
    private Date devNewTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_modify_time
     *
     * @mbggenerated
     */
    private Date devModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_proofread_time
     *
     * @mbggenerated
     */
    private Date devProofreadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_audit_time
     *
     * @mbggenerated
     */
    private Date devAuditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_authorize_time
     *
     * @mbggenerated
     */
    private Date devAuthorizeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_update_time
     *
     * @mbggenerated
     */
    private Date devUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_opeator
     *
     * @mbggenerated
     */
    private Integer devOpeator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_status
     *
     * @mbggenerated
     */
    private Integer devStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_freq_optional
     *
     * @mbggenerated
     */
    private String devFreqOptional;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_freq_FH_low
     *
     * @mbggenerated
     */
    private String devFreqFhLow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_freq_FH_mid
     *
     * @mbggenerated
     */
    private String devFreqFhMid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_freq_FH_high
     *
     * @mbggenerated
     */
    private String devFreqFhHigh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_freq_DSSS
     *
     * @mbggenerated
     */
    private String devFreqDsss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_CE101
     *
     * @mbggenerated
     */
    private String devCe101;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_CE102
     *
     * @mbggenerated
     */
    private String devCe102;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_CE106
     *
     * @mbggenerated
     */
    private String devCe106;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_CE107
     *
     * @mbggenerated
     */
    private String devCe107;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_CS101
     *
     * @mbggenerated
     */
    private String devCs101;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_CS102
     *
     * @mbggenerated
     */
    private String devCs102;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_CS103
     *
     * @mbggenerated
     */
    private String devCs103;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_CS104
     *
     * @mbggenerated
     */
    private String devCs104;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_CS105
     *
     * @mbggenerated
     */
    private String devCs105;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_CS106
     *
     * @mbggenerated
     */
    private String devCs106;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_CS109
     *
     * @mbggenerated
     */
    private String devCs109;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_CS112
     *
     * @mbggenerated
     */
    private String devCs112;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_CS114
     *
     * @mbggenerated
     */
    private String devCs114;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_CS115
     *
     * @mbggenerated
     */
    private String devCs115;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_CS116
     *
     * @mbggenerated
     */
    private String devCs116;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_RE101
     *
     * @mbggenerated
     */
    private String devRe101;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_RE102
     *
     * @mbggenerated
     */
    private String devRe102;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_RE103
     *
     * @mbggenerated
     */
    private String devRe103;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_RS101
     *
     * @mbggenerated
     */
    private String devRs101;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_RS103
     *
     * @mbggenerated
     */
    private String devRs103;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_RS105
     *
     * @mbggenerated
     */
    private String devRs105;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_advice_proofread
     *
     * @mbggenerated
     */
    private String devAdviceProofread;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_advice_audit
     *
     * @mbggenerated
     */
    private String devAdviceAudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manage_sys_develop.dev_advice_authorize
     *
     * @mbggenerated
     */
    private String devAdviceAuthorize;

    private Integer devFreSelect;

    public Integer getDevFreSelect() {return  devFreSelect;}

    public  void setDevFreSelect(Integer devFreSelect) {this.devFreSelect = devFreSelect;}

    public String getProjectList() {
        return projectList;
    }

    public void setProjectList(String projectList) {
        this.projectList = projectList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_freq_optional
     *
     * @return the value of manage_sys_develop.dev_freq_optional
     *
     * @mbggenerated
     */
    private String projectList;

    public String getDevFreqOptional() {
        return devFreqOptional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_id
     *
     * @return the value of manage_sys_develop.dev_id
     *
     * @mbggenerated
     */
    public Integer getDevId() {
        return devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_id
     *
     * @param devId the value for manage_sys_develop.dev_id
     *
     * @mbggenerated
     */
    public void setDevId(Integer devId) {
        this.devId = devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_itemid
     *
     * @return the value of manage_sys_develop.dev_itemid
     *
     * @mbggenerated
     */
    public String getDevItemid() {
        return devItemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_itemid
     *
     * @param devItemid the value for manage_sys_develop.dev_itemid
     *
     * @mbggenerated
     */
    public void setDevItemid(String devItemid) {
        this.devItemid = devItemid == null ? null : devItemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_name
     *
     * @return the value of manage_sys_develop.dev_name
     *
     * @mbggenerated
     */
    public String getDevName() {
        return devName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_name
     *
     * @param devName the value for manage_sys_develop.dev_name
     *
     * @mbggenerated
     */
    public void setDevName(String devName) {
        this.devName = devName == null ? null : devName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_subsys_eqp
     *
     * @return the value of manage_sys_develop.dev_subsys_eqp
     *
     * @mbggenerated
     */
    public Integer getDevSubsysEqp() {
        return devSubsysEqp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_subsys_eqp
     *
     * @param devSubsysEqp the value for manage_sys_develop.dev_subsys_eqp
     *
     * @mbggenerated
     */
    public void setDevSubsysEqp(Integer devSubsysEqp) {
        this.devSubsysEqp = devSubsysEqp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_subsys_eqp_name
     *
     * @return the value of manage_sys_develop.dev_subsys_eqp_name
     *
     * @mbggenerated
     */
    public String getDevSubsysEqpName() {
        return devSubsysEqpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_subsys_eqp_name
     *
     * @param devSubsysEqpName the value for manage_sys_develop.dev_subsys_eqp_name
     *
     * @mbggenerated
     */
    public void setDevSubsysEqpName(String devSubsysEqpName) {
        this.devSubsysEqpName = devSubsysEqpName == null ? null : devSubsysEqpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_subsys_eqp_model
     *
     * @return the value of manage_sys_develop.dev_subsys_eqp_model
     *
     * @mbggenerated
     */
    public String getDevSubsysEqpModel() {
        return devSubsysEqpModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_subsys_eqp_model
     *
     * @param devSubsysEqpModel the value for manage_sys_develop.dev_subsys_eqp_model
     *
     * @mbggenerated
     */
    public void setDevSubsysEqpModel(String devSubsysEqpModel) {
        this.devSubsysEqpModel = devSubsysEqpModel == null ? null : devSubsysEqpModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_subsys_eqp_num
     *
     * @return the value of manage_sys_develop.dev_subsys_eqp_num
     *
     * @mbggenerated
     */
    public String getDevSubsysEqpNum() {
        return devSubsysEqpNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_subsys_eqp_num
     *
     * @param devSubsysEqpNum the value for manage_sys_develop.dev_subsys_eqp_num
     *
     * @mbggenerated
     */
    public void setDevSubsysEqpNum(String devSubsysEqpNum) {
        this.devSubsysEqpNum = devSubsysEqpNum == null ? null : devSubsysEqpNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_supplier
     *
     * @return the value of manage_sys_develop.dev_supplier
     *
     * @mbggenerated
     */
    public String getDevSupplier() {
        return devSupplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_supplier
     *
     * @param devSupplier the value for manage_sys_develop.dev_supplier
     *
     * @mbggenerated
     */
    public void setDevSupplier(String devSupplier) {
        this.devSupplier = devSupplier == null ? null : devSupplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_primary_platform
     *
     * @return the value of manage_sys_develop.dev_primary_platform
     *
     * @mbggenerated
     */
    public Integer getDevPrimaryPlatform() {
        return devPrimaryPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_primary_platform
     *
     * @param devPrimaryPlatform the value for manage_sys_develop.dev_primary_platform
     *
     * @mbggenerated
     */
    public void setDevPrimaryPlatform(Integer devPrimaryPlatform) {
        this.devPrimaryPlatform = devPrimaryPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_secondary_platform
     *
     * @return the value of manage_sys_develop.dev_secondary_platform
     *
     * @mbggenerated
     */
    public Integer getDevSecondaryPlatform() {
        return devSecondaryPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_secondary_platform
     *
     * @param devSecondaryPlatform the value for manage_sys_develop.dev_secondary_platform
     *
     * @mbggenerated
     */
    public void setDevSecondaryPlatform(Integer devSecondaryPlatform) {
        this.devSecondaryPlatform = devSecondaryPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_attribute
     *
     * @return the value of manage_sys_develop.dev_attribute
     *
     * @mbggenerated
     */
    public Integer getDevAttribute() {
        return devAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_attribute
     *
     * @param devAttribute the value for manage_sys_develop.dev_attribute
     *
     * @mbggenerated
     */
    public void setDevAttribute(Integer devAttribute) {
        this.devAttribute = devAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_key
     *
     * @return the value of manage_sys_develop.dev_key
     *
     * @mbggenerated
     */
    public Integer getDevKey() {
        return devKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_key
     *
     * @param devKey the value for manage_sys_develop.dev_key
     *
     * @mbggenerated
     */
    public void setDevKey(Integer devKey) {
        this.devKey = devKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_install
     *
     * @return the value of manage_sys_develop.dev_install
     *
     * @mbggenerated
     */
    public Integer getDevInstall() {
        return devInstall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_install
     *
     * @param devInstall the value for manage_sys_develop.dev_install
     *
     * @mbggenerated
     */
    public void setDevInstall(Integer devInstall) {
        this.devInstall = devInstall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_GND
     *
     * @return the value of manage_sys_develop.dev_GND
     *
     * @mbggenerated
     */
    public Integer getDevGnd() {
        return devGnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_GND
     *
     * @param devGnd the value for manage_sys_develop.dev_GND
     *
     * @mbggenerated
     */
    public void setDevGnd(Integer devGnd) {
        this.devGnd = devGnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_special
     *
     * @return the value of manage_sys_develop.dev_special
     *
     * @mbggenerated
     */
    public Integer getDevSpecial() {
        return devSpecial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_special
     *
     * @param devSpecial the value for manage_sys_develop.dev_special
     *
     * @mbggenerated
     */
    public void setDevSpecial(Integer devSpecial) {
        this.devSpecial = devSpecial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_interport
     *
     * @return the value of manage_sys_develop.dev_interport
     *
     * @mbggenerated
     */
    public Integer getDevInterport() {
        return devInterport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_interport
     *
     * @param devInterport the value for manage_sys_develop.dev_interport
     *
     * @mbggenerated
     */
    public void setDevInterport(Integer devInterport) {
        this.devInterport = devInterport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_lowsensitive
     *
     * @return the value of manage_sys_develop.dev_lowsensitive
     *
     * @mbggenerated
     */
    public Integer getDevLowsensitive() {
        return devLowsensitive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_lowsensitive
     *
     * @param devLowsensitive the value for manage_sys_develop.dev_lowsensitive
     *
     * @mbggenerated
     */
    public void setDevLowsensitive(Integer devLowsensitive) {
        this.devLowsensitive = devLowsensitive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_emp
     *
     * @return the value of manage_sys_develop.dev_emp
     *
     * @mbggenerated
     */
    public Integer getDevEmp() {
        return devEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_emp
     *
     * @param devEmp the value for manage_sys_develop.dev_emp
     *
     * @mbggenerated
     */
    public void setDevEmp(Integer devEmp) {
        this.devEmp = devEmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_static
     *
     * @return the value of manage_sys_develop.dev_static
     *
     * @mbggenerated
     */
    public Integer getDevStatic() {
        return devStatic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_static
     *
     * @param devStatic the value for manage_sys_develop.dev_static
     *
     * @mbggenerated
     */
    public void setDevStatic(Integer devStatic) {
        this.devStatic = devStatic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_powerport
     *
     * @return the value of manage_sys_develop.dev_powerport
     *
     * @mbggenerated
     */
    public String getDevPowerport() {
        return devPowerport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_powerport
     *
     * @param devPowerport the value for manage_sys_develop.dev_powerport
     *
     * @mbggenerated
     */
    public void setDevPowerport(String devPowerport) {
        this.devPowerport = devPowerport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_powersupply
     *
     * @return the value of manage_sys_develop.dev_powersupply
     *
     * @mbggenerated
     */
    public String getDevPowersupply() {
        return devPowersupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_powersupply
     *
     * @param devPowersupply the value for manage_sys_develop.dev_powersupply
     *
     * @mbggenerated
     */
    public void setDevPowersupply(String devPowersupply) {
        this.devPowersupply = devPowersupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_voltage
     *
     * @return the value of manage_sys_develop.dev_voltage
     *
     * @mbggenerated
     */
    public String getDevVoltage() {
        return devVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_voltage
     *
     * @param devVoltage the value for manage_sys_develop.dev_voltage
     *
     * @mbggenerated
     */
    public void setDevVoltage(String devVoltage) {
        this.devVoltage = devVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_voltagenum
     *
     * @return the value of manage_sys_develop.dev_voltagenum
     *
     * @mbggenerated
     */
    public String getDevVoltagenum() {
        return devVoltagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_voltagenum
     *
     * @param devVoltagenum the value for manage_sys_develop.dev_voltagenum
     *
     * @mbggenerated
     */
    public void setDevVoltagenum(String devVoltagenum) {
        this.devVoltagenum = devVoltagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_antenna
     *
     * @return the value of manage_sys_develop.dev_antenna
     *
     * @mbggenerated
     */
    public Integer getDevAntenna() {
        return devAntenna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_antenna
     *
     * @param devAntenna the value for manage_sys_develop.dev_antenna
     *
     * @mbggenerated
     */
    public void setDevAntenna(Integer devAntenna) {
        this.devAntenna = devAntenna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_receive_launch
     *
     * @return the value of manage_sys_develop.dev_receive_launch
     *
     * @mbggenerated
     */
    public Integer getDevReceiveLaunch() {
        return devReceiveLaunch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_receive_launch
     *
     * @param devReceiveLaunch the value for manage_sys_develop.dev_receive_launch
     *
     * @mbggenerated
     */
    public void setDevReceiveLaunch(Integer devReceiveLaunch) {
        this.devReceiveLaunch = devReceiveLaunch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_modulation
     *
     * @return the value of manage_sys_develop.dev_modulation
     *
     * @mbggenerated
     */
    public Integer getDevModulation() {
        return devModulation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_modulation
     *
     * @param devModulation the value for manage_sys_develop.dev_modulation
     *
     * @mbggenerated
     */
    public void setDevModulation(Integer devModulation) {
        this.devModulation = devModulation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_create_time
     *
     * @return the value of manage_sys_develop.dev_create_time
     *
     * @mbggenerated
     */
    public Date getDevCreateTime() {
        return devCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_create_time
     *
     * @param devCreateTime the value for manage_sys_develop.dev_create_time
     *
     * @mbggenerated
     */
    public void setDevCreateTime(Date devCreateTime) {
        this.devCreateTime = devCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_new_time
     *
     * @return the value of manage_sys_develop.dev_new_time
     *
     * @mbggenerated
     */
    public Date getDevNewTime() {
        return devNewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_new_time
     *
     * @param devNewTime the value for manage_sys_develop.dev_new_time
     *
     * @mbggenerated
     */
    public void setDevNewTime(Date devNewTime) {
        this.devNewTime = devNewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_modify_time
     *
     * @return the value of manage_sys_develop.dev_modify_time
     *
     * @mbggenerated
     */
    public Date getDevModifyTime() {
        return devModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_modify_time
     *
     * @param devModifyTime the value for manage_sys_develop.dev_modify_time
     *
     * @mbggenerated
     */
    public void setDevModifyTime(Date devModifyTime) {
        this.devModifyTime = devModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_proofread_time
     *
     * @return the value of manage_sys_develop.dev_proofread_time
     *
     * @mbggenerated
     */
    public Date getDevProofreadTime() {
        return devProofreadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_proofread_time
     *
     * @param devProofreadTime the value for manage_sys_develop.dev_proofread_time
     *
     * @mbggenerated
     */
    public void setDevProofreadTime(Date devProofreadTime) {
        this.devProofreadTime = devProofreadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_audit_time
     *
     * @return the value of manage_sys_develop.dev_audit_time
     *
     * @mbggenerated
     */
    public Date getDevAuditTime() {
        return devAuditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_audit_time
     *
     * @param devAuditTime the value for manage_sys_develop.dev_audit_time
     *
     * @mbggenerated
     */
    public void setDevAuditTime(Date devAuditTime) {
        this.devAuditTime = devAuditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_authorize_time
     *
     * @return the value of manage_sys_develop.dev_authorize_time
     *
     * @mbggenerated
     */
    public Date getDevAuthorizeTime() {
        return devAuthorizeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_authorize_time
     *
     * @param devAuthorizeTime the value for manage_sys_develop.dev_authorize_time
     *
     * @mbggenerated
     */
    public void setDevAuthorizeTime(Date devAuthorizeTime) {
        this.devAuthorizeTime = devAuthorizeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_update_time
     *
     * @return the value of manage_sys_develop.dev_update_time
     *
     * @mbggenerated
     */
    public Date getDevUpdateTime() {
        return devUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_update_time
     *
     * @param devUpdateTime the value for manage_sys_develop.dev_update_time
     *
     * @mbggenerated
     */
    public void setDevUpdateTime(Date devUpdateTime) {
        this.devUpdateTime = devUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_opeator
     *
     * @return the value of manage_sys_develop.dev_opeator
     *
     * @mbggenerated
     */
    public Integer getDevOpeator() {
        return devOpeator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_opeator
     *
     * @param devOpeator the value for manage_sys_develop.dev_opeator
     *
     * @mbggenerated
     */
    public void setDevOpeator(Integer devOpeator) {
        this.devOpeator = devOpeator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_status
     *
     * @return the value of manage_sys_develop.dev_status
     *
     * @mbggenerated
     */
    public Integer getDevStatus() {
        return devStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_status
     *
     * @param devStatus the value for manage_sys_develop.dev_status
     *
     * @mbggenerated
     */
    public void setDevStatus(Integer devStatus) {
        this.devStatus = devStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_freq_optional
     *
     * @param devFreqOptional the value for manage_sys_develop.dev_freq_optional
     *
     * @mbggenerated
     */
    public void setDevFreqOptional(String devFreqOptional) {
        this.devFreqOptional = devFreqOptional == null ? null : devFreqOptional.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_freq_FH_low
     *
     * @return the value of manage_sys_develop.dev_freq_FH_low
     *
     * @mbggenerated
     */
    public String getDevFreqFhLow() {
        return devFreqFhLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_freq_FH_low
     *
     * @param devFreqFhLow the value for manage_sys_develop.dev_freq_FH_low
     *
     * @mbggenerated
     */
    public void setDevFreqFhLow(String devFreqFhLow) {
        this.devFreqFhLow = devFreqFhLow == null ? null : devFreqFhLow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_freq_FH_mid
     *
     * @return the value of manage_sys_develop.dev_freq_FH_mid
     *
     * @mbggenerated
     */
    public String getDevFreqFhMid() {
        return devFreqFhMid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_freq_FH_mid
     *
     * @param devFreqFhMid the value for manage_sys_develop.dev_freq_FH_mid
     *
     * @mbggenerated
     */
    public void setDevFreqFhMid(String devFreqFhMid) {
        this.devFreqFhMid = devFreqFhMid == null ? null : devFreqFhMid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_freq_FH_high
     *
     * @return the value of manage_sys_develop.dev_freq_FH_high
     *
     * @mbggenerated
     */
    public String getDevFreqFhHigh() {
        return devFreqFhHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_freq_FH_high
     *
     * @param devFreqFhHigh the value for manage_sys_develop.dev_freq_FH_high
     *
     * @mbggenerated
     */
    public void setDevFreqFhHigh(String devFreqFhHigh) {
        this.devFreqFhHigh = devFreqFhHigh == null ? null : devFreqFhHigh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_freq_DSSS
     *
     * @return the value of manage_sys_develop.dev_freq_DSSS
     *
     * @mbggenerated
     */
    public String getDevFreqDsss() {
        return devFreqDsss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_freq_DSSS
     *
     * @param devFreqDsss the value for manage_sys_develop.dev_freq_DSSS
     *
     * @mbggenerated
     */
    public void setDevFreqDsss(String devFreqDsss) {
        this.devFreqDsss = devFreqDsss == null ? null : devFreqDsss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_CE101
     *
     * @return the value of manage_sys_develop.dev_CE101
     *
     * @mbggenerated
     */
    public String getDevCe101() {
        return devCe101;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_CE101
     *
     * @param devCe101 the value for manage_sys_develop.dev_CE101
     *
     * @mbggenerated
     */
    public void setDevCe101(String devCe101) {
        this.devCe101 = devCe101 == null ? null : devCe101.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_CE102
     *
     * @return the value of manage_sys_develop.dev_CE102
     *
     * @mbggenerated
     */
    public String getDevCe102() {
        return devCe102;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_CE102
     *
     * @param devCe102 the value for manage_sys_develop.dev_CE102
     *
     * @mbggenerated
     */
    public void setDevCe102(String devCe102) {
        this.devCe102 = devCe102 == null ? null : devCe102.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_CE106
     *
     * @return the value of manage_sys_develop.dev_CE106
     *
     * @mbggenerated
     */
    public String getDevCe106() {
        return devCe106;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_CE106
     *
     * @param devCe106 the value for manage_sys_develop.dev_CE106
     *
     * @mbggenerated
     */
    public void setDevCe106(String devCe106) {
        this.devCe106 = devCe106 == null ? null : devCe106.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_CE107
     *
     * @return the value of manage_sys_develop.dev_CE107
     *
     * @mbggenerated
     */
    public String getDevCe107() {
        return devCe107;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_CE107
     *
     * @param devCe107 the value for manage_sys_develop.dev_CE107
     *
     * @mbggenerated
     */
    public void setDevCe107(String devCe107) {
        this.devCe107 = devCe107 == null ? null : devCe107.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_CS101
     *
     * @return the value of manage_sys_develop.dev_CS101
     *
     * @mbggenerated
     */
    public String getDevCs101() {
        return devCs101;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_CS101
     *
     * @param devCs101 the value for manage_sys_develop.dev_CS101
     *
     * @mbggenerated
     */
    public void setDevCs101(String devCs101) {
        this.devCs101 = devCs101 == null ? null : devCs101.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_CS102
     *
     * @return the value of manage_sys_develop.dev_CS102
     *
     * @mbggenerated
     */
    public String getDevCs102() {
        return devCs102;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_CS102
     *
     * @param devCs102 the value for manage_sys_develop.dev_CS102
     *
     * @mbggenerated
     */
    public void setDevCs102(String devCs102) {
        this.devCs102 = devCs102 == null ? null : devCs102.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_CS103
     *
     * @return the value of manage_sys_develop.dev_CS103
     *
     * @mbggenerated
     */
    public String getDevCs103() {
        return devCs103;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_CS103
     *
     * @param devCs103 the value for manage_sys_develop.dev_CS103
     *
     * @mbggenerated
     */
    public void setDevCs103(String devCs103) {
        this.devCs103 = devCs103 == null ? null : devCs103.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_CS104
     *
     * @return the value of manage_sys_develop.dev_CS104
     *
     * @mbggenerated
     */
    public String getDevCs104() {
        return devCs104;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_CS104
     *
     * @param devCs104 the value for manage_sys_develop.dev_CS104
     *
     * @mbggenerated
     */
    public void setDevCs104(String devCs104) {
        this.devCs104 = devCs104 == null ? null : devCs104.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_CS105
     *
     * @return the value of manage_sys_develop.dev_CS105
     *
     * @mbggenerated
     */
    public String getDevCs105() {
        return devCs105;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_CS105
     *
     * @param devCs105 the value for manage_sys_develop.dev_CS105
     *
     * @mbggenerated
     */
    public void setDevCs105(String devCs105) {
        this.devCs105 = devCs105 == null ? null : devCs105.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_CS106
     *
     * @return the value of manage_sys_develop.dev_CS106
     *
     * @mbggenerated
     */
    public String getDevCs106() {
        return devCs106;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_CS106
     *
     * @param devCs106 the value for manage_sys_develop.dev_CS106
     *
     * @mbggenerated
     */
    public void setDevCs106(String devCs106) {
        this.devCs106 = devCs106 == null ? null : devCs106.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_CS109
     *
     * @return the value of manage_sys_develop.dev_CS109
     *
     * @mbggenerated
     */
    public String getDevCs109() {
        return devCs109;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_CS109
     *
     * @param devCs109 the value for manage_sys_develop.dev_CS109
     *
     * @mbggenerated
     */
    public void setDevCs109(String devCs109) {
        this.devCs109 = devCs109 == null ? null : devCs109.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_CS112
     *
     * @return the value of manage_sys_develop.dev_CS112
     *
     * @mbggenerated
     */
    public String getDevCs112() {
        return devCs112;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_CS112
     *
     * @param devCs112 the value for manage_sys_develop.dev_CS112
     *
     * @mbggenerated
     */
    public void setDevCs112(String devCs112) {
        this.devCs112 = devCs112 == null ? null : devCs112.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_CS114
     *
     * @return the value of manage_sys_develop.dev_CS114
     *
     * @mbggenerated
     */
    public String getDevCs114() {
        return devCs114;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_CS114
     *
     * @param devCs114 the value for manage_sys_develop.dev_CS114
     *
     * @mbggenerated
     */
    public void setDevCs114(String devCs114) {
        this.devCs114 = devCs114 == null ? null : devCs114.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_CS115
     *
     * @return the value of manage_sys_develop.dev_CS115
     *
     * @mbggenerated
     */
    public String getDevCs115() {
        return devCs115;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_CS115
     *
     * @param devCs115 the value for manage_sys_develop.dev_CS115
     *
     * @mbggenerated
     */
    public void setDevCs115(String devCs115) {
        this.devCs115 = devCs115 == null ? null : devCs115.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_CS116
     *
     * @return the value of manage_sys_develop.dev_CS116
     *
     * @mbggenerated
     */
    public String getDevCs116() {
        return devCs116;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_CS116
     *
     * @param devCs116 the value for manage_sys_develop.dev_CS116
     *
     * @mbggenerated
     */
    public void setDevCs116(String devCs116) {
        this.devCs116 = devCs116 == null ? null : devCs116.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_RE101
     *
     * @return the value of manage_sys_develop.dev_RE101
     *
     * @mbggenerated
     */
    public String getDevRe101() {
        return devRe101;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_RE101
     *
     * @param devRe101 the value for manage_sys_develop.dev_RE101
     *
     * @mbggenerated
     */
    public void setDevRe101(String devRe101) {
        this.devRe101 = devRe101 == null ? null : devRe101.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_RE102
     *
     * @return the value of manage_sys_develop.dev_RE102
     *
     * @mbggenerated
     */
    public String getDevRe102() {
        return devRe102;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_RE102
     *
     * @param devRe102 the value for manage_sys_develop.dev_RE102
     *
     * @mbggenerated
     */
    public void setDevRe102(String devRe102) {
        this.devRe102 = devRe102 == null ? null : devRe102.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_RE103
     *
     * @return the value of manage_sys_develop.dev_RE103
     *
     * @mbggenerated
     */
    public String getDevRe103() {
        return devRe103;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_RE103
     *
     * @param devRe103 the value for manage_sys_develop.dev_RE103
     *
     * @mbggenerated
     */
    public void setDevRe103(String devRe103) {
        this.devRe103 = devRe103 == null ? null : devRe103.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_RS101
     *
     * @return the value of manage_sys_develop.dev_RS101
     *
     * @mbggenerated
     */
    public String getDevRs101() {
        return devRs101;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_RS101
     *
     * @param devRs101 the value for manage_sys_develop.dev_RS101
     *
     * @mbggenerated
     */
    public void setDevRs101(String devRs101) {
        this.devRs101 = devRs101 == null ? null : devRs101.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_RS103
     *
     * @return the value of manage_sys_develop.dev_RS103
     *
     * @mbggenerated
     */
    public String getDevRs103() {
        return devRs103;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_RS103
     *
     * @param devRs103 the value for manage_sys_develop.dev_RS103
     *
     * @mbggenerated
     */
    public void setDevRs103(String devRs103) {
        this.devRs103 = devRs103 == null ? null : devRs103.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_RS105
     *
     * @return the value of manage_sys_develop.dev_RS105
     *
     * @mbggenerated
     */
    public String getDevRs105() {
        return devRs105;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_RS105
     *
     * @param devRs105 the value for manage_sys_develop.dev_RS105
     *
     * @mbggenerated
     */
    public void setDevRs105(String devRs105) {
        this.devRs105 = devRs105 == null ? null : devRs105.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_advice_proofread
     *
     * @return the value of manage_sys_develop.dev_advice_proofread
     *
     * @mbggenerated
     */
    public String getDevAdviceProofread() {
        return devAdviceProofread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_advice_proofread
     *
     * @param devAdviceProofread the value for manage_sys_develop.dev_advice_proofread
     *
     * @mbggenerated
     */
    public void setDevAdviceProofread(String devAdviceProofread) {
        this.devAdviceProofread = devAdviceProofread == null ? null : devAdviceProofread.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_advice_audit
     *
     * @return the value of manage_sys_develop.dev_advice_audit
     *
     * @mbggenerated
     */
    public String getDevAdviceAudit() {
        return devAdviceAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_advice_audit
     *
     * @param devAdviceAudit the value for manage_sys_develop.dev_advice_audit
     *
     * @mbggenerated
     */
    public void setDevAdviceAudit(String devAdviceAudit) {
        this.devAdviceAudit = devAdviceAudit == null ? null : devAdviceAudit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manage_sys_develop.dev_advice_authorize
     *
     * @return the value of manage_sys_develop.dev_advice_authorize
     *
     * @mbggenerated
     */
    public String getDevAdviceAuthorize() {
        return devAdviceAuthorize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manage_sys_develop.dev_advice_authorize
     *
     * @param devAdviceAuthorize the value for manage_sys_develop.dev_advice_authorize
     *
     * @mbggenerated
     */
    public void setDevAdviceAuthorize(String devAdviceAuthorize) {
        this.devAdviceAuthorize = devAdviceAuthorize == null ? null : devAdviceAuthorize.trim();
    }
}