package cn.gjb151b.outline.model;

import java.util.Date;

public class OutlineUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outline_user_info.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outline_user_info.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outline_user_info.user_password
     *
     * @mbggenerated
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outline_user_info.user_level
     *
     * @mbggenerated
     */
    private Integer userLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outline_user_info.user_create_time
     *
     * @mbggenerated
     */
    private Date userCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outline_user_info.user_update_time
     *
     * @mbggenerated
     */
    private Date userUpdateTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outline_user_info.user_new
     *
     * @mbggenerated
     */
    private String userNew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outline_user_info.user_proofread
     *
     * @mbggenerated
     */
    private String userProofread;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outline_user_info.user_audit
     *
     * @mbggenerated
     */
    private String userAudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outline_user_info.user_authorize
     *
     * @mbggenerated
     */
    private String userAuthorize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outline_user_info.user_remark
     *
     * @mbggenerated
     */
    private String userRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outline_user_info.user_id
     *
     * @return the value of outline_user_info.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outline_user_info.user_id
     *
     * @param userId the value for outline_user_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outline_user_info.user_name
     *
     * @return the value of outline_user_info.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outline_user_info.user_name
     *
     * @param userName the value for outline_user_info.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outline_user_info.user_password
     *
     * @return the value of outline_user_info.user_password
     *
     * @mbggenerated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outline_user_info.user_password
     *
     * @param userPassword the value for outline_user_info.user_password
     *
     * @mbggenerated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outline_user_info.user_level
     *
     * @return the value of outline_user_info.user_level
     *
     * @mbggenerated
     */
    public Integer getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outline_user_info.user_level
     *
     * @param userLevel the value for outline_user_info.user_level
     *
     * @mbggenerated
     */
    public void setUserLevel(Integer userLevel) {
        this.userLevel = userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outline_user_info.user_create_time
     *
     * @return the value of outline_user_info.user_create_time
     *
     * @mbggenerated
     */
    public Date getUserCreateTime() {
        return userCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outline_user_info.user_create_time
     *
     * @param userCreateTime the value for outline_user_info.user_create_time
     *
     * @mbggenerated
     */
    public void setUserCreateTime(Date userCreateTime) {
        this.userCreateTime = userCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outline_user_info.user_update_time
     *
     * @return the value of outline_user_info.user_update_time
     *
     * @mbggenerated
     */
    public Date getUserUpdateTime() {
        return userUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outline_user_info.user_update_time
     *
     * @param userUpdateTime the value for outline_user_info.user_update_time
     *
     * @mbggenerated
     */
    public void setUserUpdateTime(Date userUpdateTime) {
        this.userUpdateTime = userUpdateTime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outline_user_info.user_new
     *
     * @return the value of outline_user_info.user_new
     *
     * @mbggenerated
     */
    public String getUserNew() {
        return userNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outline_user_info.user_new
     *
     * @param userNew the value for outline_user_info.user_new
     *
     * @mbggenerated
     */
    public void setUserNew(String userNew) {
        this.userNew = userNew == null ? null : userNew.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outline_user_info.user_proofread
     *
     * @return the value of outline_user_info.user_proofread
     *
     * @mbggenerated
     */
    public String getUserProofread() {
        return userProofread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outline_user_info.user_proofread
     *
     * @param userProofread the value for outline_user_info.user_proofread
     *
     * @mbggenerated
     */
    public void setUserProofread(String userProofread) {
        this.userProofread = userProofread == null ? null : userProofread.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outline_user_info.user_audit
     *
     * @return the value of outline_user_info.user_audit
     *
     * @mbggenerated
     */
    public String getUserAudit() {
        return userAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outline_user_info.user_audit
     *
     * @param userAudit the value for outline_user_info.user_audit
     *
     * @mbggenerated
     */
    public void setUserAudit(String userAudit) {
        this.userAudit = userAudit == null ? null : userAudit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outline_user_info.user_authorize
     *
     * @return the value of outline_user_info.user_authorize
     *
     * @mbggenerated
     */
    public String getUserAuthorize() {
        return userAuthorize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outline_user_info.user_authorize
     *
     * @param userAuthorize the value for outline_user_info.user_authorize
     *
     * @mbggenerated
     */
    public void setUserAuthorize(String userAuthorize) {
        this.userAuthorize = userAuthorize == null ? null : userAuthorize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outline_user_info.user_remark
     *
     * @return the value of outline_user_info.user_remark
     *
     * @mbggenerated
     */
    public String getUserRemark() {
        return userRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outline_user_info.user_remark
     *
     * @param userRemark the value for outline_user_info.user_remark
     *
     * @mbggenerated
     */
    public void setUserRemark(String userRemark) {
        this.userRemark = userRemark == null ? null : userRemark.trim();
    }
}